# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: casisco.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='casisco.proto',
  package='casisco',
  syntax='proto3',
  serialized_pb=_b('\n\rcasisco.proto\x12\x07\x63\x61sisco\"A\n\x10UserRegisterInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"y\n\x12UserRegisterStatus\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".casisco.UserRegisterStatus.Status\"/\n\x06Status\x12\x06\n\x02ok\x10\x00\x12\r\n\tnameTaken\x10\x01\x12\x0e\n\nemailTaken\x10\x02\x32S\n\x07\x43\x61sisco\x12H\n\x0cregisterUser\x12\x19.casisco.UserRegisterInfo\x1a\x1b.casisco.UserRegisterStatus\"\x00\x62\x06proto3')
)



_USERREGISTERSTATUS_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='casisco.UserRegisterStatus.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ok', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='nameTaken', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='emailTaken', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=167,
  serialized_end=214,
)
_sym_db.RegisterEnumDescriptor(_USERREGISTERSTATUS_STATUS)


_USERREGISTERINFO = _descriptor.Descriptor(
  name='UserRegisterInfo',
  full_name='casisco.UserRegisterInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='casisco.UserRegisterInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='casisco.UserRegisterInfo.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='casisco.UserRegisterInfo.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=91,
)


_USERREGISTERSTATUS = _descriptor.Descriptor(
  name='UserRegisterStatus',
  full_name='casisco.UserRegisterStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='casisco.UserRegisterStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERREGISTERSTATUS_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=214,
)

_USERREGISTERSTATUS.fields_by_name['status'].enum_type = _USERREGISTERSTATUS_STATUS
_USERREGISTERSTATUS_STATUS.containing_type = _USERREGISTERSTATUS
DESCRIPTOR.message_types_by_name['UserRegisterInfo'] = _USERREGISTERINFO
DESCRIPTOR.message_types_by_name['UserRegisterStatus'] = _USERREGISTERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRegisterInfo = _reflection.GeneratedProtocolMessageType('UserRegisterInfo', (_message.Message,), dict(
  DESCRIPTOR = _USERREGISTERINFO,
  __module__ = 'casisco_pb2'
  # @@protoc_insertion_point(class_scope:casisco.UserRegisterInfo)
  ))
_sym_db.RegisterMessage(UserRegisterInfo)

UserRegisterStatus = _reflection.GeneratedProtocolMessageType('UserRegisterStatus', (_message.Message,), dict(
  DESCRIPTOR = _USERREGISTERSTATUS,
  __module__ = 'casisco_pb2'
  # @@protoc_insertion_point(class_scope:casisco.UserRegisterStatus)
  ))
_sym_db.RegisterMessage(UserRegisterStatus)



_CASISCO = _descriptor.ServiceDescriptor(
  name='Casisco',
  full_name='casisco.Casisco',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=216,
  serialized_end=299,
  methods=[
  _descriptor.MethodDescriptor(
    name='registerUser',
    full_name='casisco.Casisco.registerUser',
    index=0,
    containing_service=None,
    input_type=_USERREGISTERINFO,
    output_type=_USERREGISTERSTATUS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CASISCO)

DESCRIPTOR.services_by_name['Casisco'] = _CASISCO

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class CasiscoStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.registerUser = channel.unary_unary(
          '/casisco.Casisco/registerUser',
          request_serializer=UserRegisterInfo.SerializeToString,
          response_deserializer=UserRegisterStatus.FromString,
          )


  class CasiscoServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def registerUser(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_CasiscoServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'registerUser': grpc.unary_unary_rpc_method_handler(
            servicer.registerUser,
            request_deserializer=UserRegisterInfo.FromString,
            response_serializer=UserRegisterStatus.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'casisco.Casisco', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaCasiscoServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def registerUser(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaCasiscoStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def registerUser(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    registerUser.future = None


  def beta_create_Casisco_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('casisco.Casisco', 'registerUser'): UserRegisterInfo.FromString,
    }
    response_serializers = {
      ('casisco.Casisco', 'registerUser'): UserRegisterStatus.SerializeToString,
    }
    method_implementations = {
      ('casisco.Casisco', 'registerUser'): face_utilities.unary_unary_inline(servicer.registerUser),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Casisco_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('casisco.Casisco', 'registerUser'): UserRegisterInfo.SerializeToString,
    }
    response_deserializers = {
      ('casisco.Casisco', 'registerUser'): UserRegisterStatus.FromString,
    }
    cardinalities = {
      'registerUser': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'casisco.Casisco', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
