# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import casisco_pb2 as casisco__pb2


class CasiscoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.registerUser = channel.unary_unary(
        '/casisco.Casisco/registerUser',
        request_serializer=casisco__pb2.UserRegisterInfo.SerializeToString,
        response_deserializer=casisco__pb2.UserRegisterStatus.FromString,
        )


class CasiscoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def registerUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CasiscoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'registerUser': grpc.unary_unary_rpc_method_handler(
          servicer.registerUser,
          request_deserializer=casisco__pb2.UserRegisterInfo.FromString,
          response_serializer=casisco__pb2.UserRegisterStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'casisco.Casisco', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
